### ISSUE TITLE
Cannot upload cookbooks after pulling the latest changes.

### ISSUE THREAD

**Issue by chris-elford-metaswitch** [Metaswitch/chef#277]
When I tried to upload the clearwater cookbook after pulling the latest changes from master, I hit the following crash trying to upload my cookbook:

```
/home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife/core/subcommand_loader.rb:37:in `load': cannot load such file -- /home/ubuntu/chef-p                rivate/.chef/plugins/knife/knife-shared-config-update.rb (LoadError)
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife/core/subcommand_loader.rb:37:in `block in load_commands'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife/core/subcommand_loader.rb:37:in `each'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife.rb:119:in `load_commands'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/knife.rb:167:in `run'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/lib/chef/application/knife.rb:123:in `run'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/chef-11.4.0/bin/knife:25:in `<top (required)>'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/knife:23:in `load'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/knife:23:in `<main>'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

The file /home/ubuntu/chef-private/.chef/plugins/knife/knife-shared-config-update.rb is a broken link. That makes sense as that file has been removed by https://github.com/Metaswitch/chef/commit/36df864fe7a4b137cd9326d9287b28cbcf52c07b. 

I worked around this by deleting the .chef folder in chef-private, but I suspect there is a right way of doing this which we should document.

**Comment by chris-elford-metaswitch** [comment]
Ellie, I'm passing this to you as I think this is the result of your recent changes.
